version: "3"

services:
  confd:
    build: ./confd
    volumes:
      - ./target:/target
      - ~/.aws:/root/.aws
    environment:
      - AWS_PROFILE

  awscli:
    build: ./awscli
    volumes:
      - ./target:/target
      - ~/.aws:/root/.aws
    environment:
      - AWS_PROFILE
